allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@swc/core': true
  core-js: true
  esbuild: set this to true or false
  msw: true
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
