"use server";

import type { Prisma } from "@prisma/client";
import type { StockMovement, MovementType } from "@/lib/types";
import {
  toStockMovement,
  toExpiringLot,
  type MovementJoinedRow,
  type ExpiringLot,
} from "@/lib/mappers";
import {
  withAuth,
  withCompany,
  warehouseScope,
  ok,
  parseInput,
  z,
  ERR,
} from "@/lib/server";
import { applyStockMovement, allowNegativeStock } from "@/lib/inventory/engine";

// ============================================
// GET STOCK MOVEMENTS
// ============================================
export const getStockMovements = withAuth<
  { search?: string; type?: string; warehouseId?: string; limit?: number } | undefined,
  StockMovement[]
>(async (ctx, filters) => {
  const where: Prisma.StockMovementWhereInput = {
    companyId: ctx.companyId,
  };
  if (filters?.type && filters.type !== "all") {
    where.movementType = filters.type as MovementType;
  }
  if (filters?.warehouseId) {
    where.OR = [
      { fromWarehouseId: filters.warehouseId },
      { toWarehouseId: filters.warehouseId },
    ];
  }
  if (filters?.search) {
    where.product = {
      OR: [
        { name: { contains: filters.search, mode: "insensitive" } },
        { sku: { contains: filters.search, mode: "insensitive" } },
      ],
    };
  }

  // Warehouse staff only see movements touching their assigned warehouses.
  // Composed via AND so it doesn't clobber the optional `warehouseId` filter above.
  const scope = warehouseScope(ctx);
  if (scope) {
    where.AND = [
      {
        OR: [
          { fromWarehouseId: { in: scope } },
          { toWarehouseId: { in: scope } },
        ],
      },
    ];
  }

  const rows = await ctx.prisma.stockMovement.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: filters?.limit ?? undefined,
    include: {
      product: { select: { name: true, sku: true } },
      fromWarehouse: { select: { name: true } },
      toWarehouse: { select: { name: true } },
      user: { select: { fullName: true } },
    },
  });

  return ok(rows.map((row) => toStockMovement(row as MovementJoinedRow)));
});

// ============================================
// CREATE STOCK MOVEMENT
// ============================================
const movementInputSchema = z.object({
  productId: z.string(),
  type: z.enum(["in", "out", "transfer", "adjustment"]),
  quantity: z.number().positive("Miktar 0'dan büyük olmalı"),
  warehouseId: z.string(),
  toWarehouseId: z.string().optional(),
  lotNumber: z.string().optional(),
  serialNumber: z.string().optional(),
  expiryDate: z.string().optional(),
  reason: z.string().optional(),
  reference: z.string().optional(),
  unitCost: z.number().nonnegative().optional(),
  /**
   * Stable id generated by the offline queue so a replayed action is applied at
   * most once (idempotency). Optional for direct online calls.
   */
  clientActionId: z.string().optional(),
});

export const createStockMovement = withCompany<
  z.input<typeof movementInputSchema>,
  void
>(async (ctx, raw) => {
  const data = parseInput(movementInputSchema, raw);

  // Verify the product belongs to the current company before doing anything.
  const product = await ctx.prisma.product.findFirst({
    where: { id: data.productId, companyId: ctx.companyId },
    select: { id: true, purchasePrice: true, tracksSerial: true },
  });
  if (!product) throw ERR.notFound("Ürün");

  // Serial-tracked products require a serial number on inbound movements.
  if (product.tracksSerial && data.type === "in" && !data.serialNumber) {
    throw ERR.validation("Bu ürün için seri no zorunlu", "serialNumber");
  }

  // Transfers require a destination warehouse distinct from the source.
  if (data.type === "transfer") {
    if (!data.toWarehouseId) {
      throw ERR.validation("Transfer için hedef depo seçin", "toWarehouseId");
    }
    if (data.toWarehouseId === data.warehouseId) {
      throw ERR.validation("Kaynak ve hedef depo aynı olamaz", "toWarehouseId");
    }
  }

  const fromWarehouseId =
    data.type === "out" || data.type === "transfer" ? data.warehouseId : null;
  const toWarehouseId =
    data.type === "in" ? data.warehouseId : data.toWarehouseId ?? null;

  // Warehouse staff may only move stock into/out of warehouses they're assigned to.
  const scope = warehouseScope(ctx);
  if (scope) {
    const touched = [fromWarehouseId, toWarehouseId].filter(Boolean) as string[];
    const outOfScope = touched.find((id) => !scope.includes(id));
    if (outOfScope) {
      throw ERR.validation("Bu depoda işlem yapma yetkiniz yok", "warehouseId");
    }
  }

  // Idempotency: if this offline action was already applied, treat as success.
  if (data.clientActionId) {
    const dup = await ctx.prisma.stockMovement.findFirst({
      where: {
        companyId: ctx.companyId,
        referenceType: "offline_sync",
        referenceNumber: data.clientActionId,
      },
      select: { id: true },
    });
    if (dup) return ok();
  }

  const unitCost =
    data.unitCost ?? (data.type === "in" ? Number(product.purchasePrice) : 0);

  await ctx.prisma.$transaction(async (tx) => {
    const allowNegative = await allowNegativeStock(tx, ctx.companyId);
    await applyStockMovement(tx, {
      companyId: ctx.companyId,
      productId: data.productId,
      movementType: data.type,
      quantity: data.quantity,
      fromWarehouseId,
      toWarehouseId,
      lotNumber: data.lotNumber ?? null,
      serialNumber: data.serialNumber ?? null,
      expiryDate: data.expiryDate ?? null,
      unitCost,
      reason: data.reason ?? "manual",
      referenceType: data.clientActionId ? "offline_sync" : "manual",
      referenceNumber: data.clientActionId ?? data.reference ?? null,
      userId: ctx.userId,
      allowNegative,
    });
  });

  return ok();
});

// ============================================
// GET EXPIRING LOTS
// ============================================
export const getExpiringLots = withAuth<void, ExpiringLot[]>(async (ctx) => {
  const rows = await ctx.prisma.expiringLot.findMany({
    where: { companyId: ctx.companyId },
    orderBy: { expiryDate: "asc" },
  });
  return ok(rows.map(toExpiringLot));
});

// ============================================
// GET DASHBOARD STATS
// ============================================
export interface DashboardStats {
  totalProducts: number;
  totalStock: number;
  lowStock: number;
  expiringCount: number;
}

export const getDashboardStats = withAuth<void, DashboardStats>(async (ctx) => {
  const [totalProducts, inventoryRows, expiringCount, lowStockCount] =
    await Promise.all([
      ctx.prisma.product.count({
        where: { companyId: ctx.companyId, isActive: true },
      }),
      ctx.prisma.inventory.findMany({
        where: { companyId: ctx.companyId },
        select: { quantity: true },
      }),
      ctx.prisma.expiringLot.count({
        where: {
          companyId: ctx.companyId,
          daysLeft: { gt: 0, lte: 30 },
        },
      }),
      ctx.prisma.productStockSummary.count({
        where: {
          companyId: ctx.companyId,
          stockStatus: { in: ["low", "critical"] },
        },
      }),
    ]);

  const totalStock = inventoryRows.reduce(
    (sum, r) => sum + Number(r.quantity),
    0
  );

  return ok({
    totalProducts,
    totalStock,
    lowStock: lowStockCount,
    expiringCount,
  });
});
